const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Fix login bug",
        taskDescription: "Resolve the login authentication issue in React app",
        taskDate: "2025-09-05",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Update README",
        taskDescription: "Add installation steps and usage examples",
        taskDate: "2025-09-07",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "UI polish",
        taskDescription: "Improve button hover effects",
        taskDate: "2025-09-10",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskSummary: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    firstName: "Diya",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "API integration",
        taskDescription: "Connect employee dashboard with backend API",
        taskDate: "2025-09-06",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Write unit tests",
        taskDescription: "Add Jest tests for user service",
        taskDate: "2025-09-09",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix CSS issues",
        taskDescription: "Resolve styling inconsistencies in profile page",
        taskDate: "2025-09-08",
        category: "Design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskSummary: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 3,
    firstName: "Ishaan",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Optimize queries",
        taskDescription: "Improve database performance for analytics",
        taskDate: "2025-09-10",
        category: "Database",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Bug triage",
        taskDescription: "Check reported issues and categorize them",
        taskDate: "2025-09-07",
        category: "QA",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Team meeting",
        taskDescription: "Weekly sync-up with project team",
        taskDate: "2025-09-06",
        category: "Management",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskSummary: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 4,
    firstName: "Meera",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Onboarding docs",
        taskDescription: "Prepare onboarding guide for new hires",
        taskDate: "2025-09-09",
        category: "Documentation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Design mockups",
        taskDescription: "Create UI mockups for dashboard revamp",
        taskDate: "2025-09-11",
        category: "Design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Fix navbar",
        taskDescription: "Correct alignment and responsiveness issues",
        taskDate: "2025-09-08",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Deploy staging",
        taskDescription: "Deploy latest code to staging environment",
        taskDate: "2025-09-12",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskSummary: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 5,
    firstName: "Riya",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Write blog post",
        taskDescription: "Document lessons learned from last sprint",
        taskDate: "2025-09-07",
        category: "Content",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Security audit",
        taskDescription: "Review application for security issues",
        taskDate: "2025-09-09",
        category: "Security",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Refactor code",
        taskDescription: "Clean up old utility functions",
        taskDate: "2025-09-10",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Prepare demo",
        taskDescription: "Create demo for client presentation",
        taskDate: "2025-09-13",
        category: "Management",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskSummary: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
];

const admin = [
  {
    id: 1,
    firstName: "Arjun",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
  //make sure to stringify
};

export const getLocalStorage = () => {
  const EmpData = JSON.parse(localStorage.getItem("employees"));
  const AdmData = JSON.parse(localStorage.getItem("admin"));
  return { EmpData, AdmData };
};
