const admin = [
  {
    id: 1,
    firstName: "Arjun",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  if (!localStorage.getItem("employees")) {
    const employees = [
      {
        id: 1,
        firstName: "Aarav",
        email: "employee1@example.com",
        password: "123",
        tasks: [
          {
            title: "Fix login bug",
            desc: "Resolve the login authentication issue in React app",
            date: "2025-09-05",
            category: "Development",
            active: true,
            newTask: true,
            completed: false,
            failed: false,
          },
          {
            title: "Update README",
            desc: "Add installation steps and usage examples",
            date: "2025-09-07",
            category: "Documentation",
            active: false,
            newTask: false,
            completed: true,
            failed: false,
          },
          {
            title: "UI polish",
            desc: "Improve button hover effects",
            date: "2025-09-10",
            category: "Design",
            active: true,
            newTask: false,
            completed: false,
            failed: false,
          },
        ],
        taskSummary: {
          active: 2,
          newTask: 1,
          completed: 1,
          failed: 0,
        },
      },
      {
        id: 2,
        firstName: "Diya",
        email: "employee2@example.com",
        password: "123",
        tasks: [
          {
            title: "API integration",
            desc: "Connect employee dashboard with backend API",
            date: "2025-09-06",
            category: "Development",
            active: true,
            newTask: true,
            completed: false,
            failed: false,
          },
          {
            title: "Write unit tests",
            desc: "Add Jest tests for user service",
            date: "2025-09-09",
            category: "Testing",
            active: true,
            newTask: false,
            completed: false,
            failed: false,
          },
          {
            title: "Fix CSS issues",
            desc: "Resolve styling inconsistencies in profile page",
            date: "2025-09-08",
            category: "Design",
            active: false,
            newTask: false,
            completed: true,
            failed: false,
          },
        ],
        taskSummary: {
          active: 2,
          newTask: 1,
          completed: 1,
          failed: 1,
        },
      },
      {
        id: 3,
        firstName: "Ishaan",
        email: "employee3@example.com",
        password: "123",
        tasks: [
          {
            title: "Optimize queries",
            desc: "Improve database performance for analytics",
            date: "2025-09-10",
            category: "Database",
            active: true,
            newTask: true,
            completed: false,
            failed: false,
          },
          {
            title: "Bug triage",
            desc: "Check reported issues and categorize them",
            date: "2025-09-07",
            category: "QA",
            active: false,
            newTask: false,
            completed: true,
            failed: false,
          },
          {
            title: "Team meeting",
            desc: "Weekly sync-up with project team",
            date: "2025-09-06",
            category: "Management",
            active: true,
            newTask: false,
            completed: false,
            failed: false,
          },
        ],
        taskSummary: {
          active: 2,
          newTask: 1,
          completed: 1,
          failed: 0,
        },
      },
      {
        id: 4,
        firstName: "Meera",
        email: "employee4@example.com",
        password: "123",
        tasks: [
          {
            title: "Onboarding docs",
            desc: "Prepare onboarding guide for new hires",
            date: "2025-09-09",
            category: "Documentation",
            active: true,
            newTask: true,
            completed: false,
            failed: false,
          },
          {
            title: "Design mockups",
            desc: "Create UI mockups for dashboard revamp",
            date: "2025-09-11",
            category: "Design",
            active: false,
            newTask: false,
            completed: true,
            failed: false,
          },
          {
            title: "Fix navbar",
            desc: "Correct alignment and responsiveness issues",
            date: "2025-09-08",
            category: "Development",
            active: true,
            newTask: false,
            completed: false,
            failed: false,
          },
          {
            title: "Deploy staging",
            desc: "Deploy latest code to staging environment",
            date: "2025-09-12",
            category: "DevOps",
            active: false,
            newTask: false,
            completed: false,
            failed: true,
          },
        ],
        taskSummary: {
          active: 2,
          newTask: 1,
          completed: 1,
          failed: 1,
        },
      },
      {
        id: 5,
        firstName: "Riya",
        email: "employee5@example.com",
        password: "123",
        tasks: [
          {
            title: "Write blog post",
            desc: "Document lessons learned from last sprint",
            date: "2025-09-07",
            category: "Content",
            active: true,
            newTask: true,
            completed: false,
            failed: false,
          },
          {
            title: "Security audit",
            desc: "Review application for security issues",
            date: "2025-09-09",
            category: "Security",
            active: true,
            newTask: false,
            completed: false,
            failed: false,
          },
          {
            title: "Refactor code",
            desc: "Clean up old utility functions",
            date: "2025-09-10",
            category: "Development",
            active: false,
            newTask: false,
            completed: true,
            failed: false,
          },
          {
            title: "Prepare demo",
            desc: "Create demo for client presentation",
            date: "2025-09-13",
            category: "Management",
            active: false,
            newTask: false,
            completed: false,
            failed: true,
          },
        ],
        taskSummary: {
          active: 2,
          newTask: 1,
          completed: 1,
          failed: 1,
        },
      },
    ];
    localStorage.setItem("employees", JSON.stringify(employees));
  }
  //make sure to stringify
  if (!localStorage.getItem("admin")) {
    localStorage.setItem("admin", JSON.stringify(admin));
  }
};
export const getLocalStorage = () => {
  const EmpData = JSON.parse(localStorage.getItem("employees")) || [];
  const AdmData = JSON.parse(localStorage.getItem("admin")) || [];
  return { EmpData, AdmData };
};
